server:
  port: ${PORT:9200}

spring:
  application:
    name: matlab-server

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.31.177:8761/eureka
  instance:
    prefer-ip-address: true

matlab-client:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList