server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: matlab-server-two.herokuapp.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://matlab-server-two.herokuapp.com/eureka/
